- hosts: Clientes

  become: true

  tasks:

   - name: Instalación del archivo segun.py en el servidor
     template:  
       src: ~/Desarrollo/SegungoPy/CreaZk.py
       dest: /usr/local/bin/
       mode: '0755'
